# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/src/infrastructure/terraform"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[terraform] "
    open-pull-requests-limit: 10

  # - package-ecosystem: "npm"
  #   directory: "/src/web/hippo-booking"
  #   schedule:
  #     interval: "weekly"
  #   commit-message:
  #     prefix: "[npm] "
  #   open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget] "
    open-pull-requests-limit: 10
