# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/src/infrastructure/terraform"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[terraform] "
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[github actions] "
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/src/web/hippo-booking"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[npm] "
    open-pull-requests-limit: 2

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[nuget] "
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "AWSSDK.*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "Microsoft.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Serilog.AspNetCore"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "Npgsql.EntityFrameworkCore.PostgreSQL"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "FluentAssertions"
        update-types: [ "version-update:semver-major" ]
