name: 'hippo-booking'
services:
  booking-web:
    build:
        context: ../../web/hippo-booking
        dockerfile: Dockerfile
    ports:
        - "5173:5173"
    environment:
      BUILD_COMMAND: "yarn e2e"
  booking-api:
    build:
        context: ../../
        dockerfile: api/Hippo.Booking.API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
        - "7249:8080"
    environment:
        ASPNETCORE_ENVIRONMENT: EndToEnd
        UseMockAuth: true
        AllowedOrigins: https://localhost:5173
        ConnectionStrings__HippoBookingDbContext: Host=postgres;Port=5432;Database=HippoBooking_EndToEnd;Username=postgres;Password=postgres
        ConnectionStrings__HangfireDbContext: Host=postgres;Port=5432;Database=Hangfire_EndToEnd;Username=postgres;Password=postgres