version: '3'
name: 'hippo-booking'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mystrong!Pa55word"
      ACCEPT_EULA: Y
    volumes:
      - "./sql/data:/var/opt/mssql/data"
      - "./sql/log:/var/opt/mssql/log"
      - "./sql/secrets:/var/opt/mssql/secrets"
      
#  postgres:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data