version: '3'
name: 'hippo-booking'
services:
  booking-web:
    build:
        context: ../../web/hippo-booking
        dockerfile: Dockerfile
    ports:
        - "5173:5173"
  booking-api:
    build:
        context: ../../
        dockerfile: api/Hippo.Booking.API/Dockerfile
    depends_on:
      - postgres
    ports:
        - "7249:8080"
    environment:
        ASPNETCORE_ENVIRONMENT: EndToEnd
        AllowedOrigins: https://localhost:5173
        ConnectionStrings__HippoBookingDbContext: Host=postgres;Port=5432;Database=HippoBooking_EndToEnd;Username=postgres;Password=postgres