name: Main CI

on:
  push:
    branches: [ "main", "feat/ci-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
        
  build-backend:
    name: 'Build Back End API'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --no-restore

      - name: Run Application Unit Tests
        run: dotnet test api/tests/**/Hippo.Booking.Application.Tests.csproj --no-build --verbosity normal

      - name: Run Core Unit Tests
        run: dotnet test api/tests/**/Hippo.Booking.Core.Tests.csproj --no-build --verbosity normal
          
  build-frontend:
    name: 'Build Front End App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Enable Corepack
        run: corepack enable

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ./src/web/hippo-booking

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: ./src/web/hippo-booking
          
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: ci-test
          dir: ./src/web/hippo-booking
          
      - name: Run Cypress Tests
        working-directory: ./src/web/hippo-booking
        run: |
          npx cypress run --component
          
#  pulumi-test:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      id-token: write
#    environment:
#      name: 'Development'
#    defaults:
#      run:
#        working-directory: ./src/infrastructure/Hippo.Booking.Deploy.Azure
#    steps:
#      - uses: actions/checkout@v4
#        
#      - name: 'Az CLI login'
#        uses: azure/login@v1
#        with:
#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          
#      - name: 'Pulumi Install'
#        uses: pulumi/actions@v5
#          
#      - name: 'Set Pulumi Secret Environment Variable'
#        run: |
#          PULUMI_CONFIG_PASSPHRASE=${{ secrets.PULUMI_SECRET_DEV }}
#          echo "PULUMI_CONFIG_PASSPHRASE=${PULUMI_CONFIG_PASSPHRASE}" >>${GITHUB_ENV}
#          
#      - name: 'Pulumi Login'
#        run: pulumi login "${{ secrets.PULUMI_AZURE_STATE_URL }}"
#        
#      - name: 'Pulumi Refresh'
#        run: pulumi refresh --stack dev --yes
#        
#      - name: 'Pulumi Up'
#        run: pulumi up --stack dev --yes
#         
#      - name: 'Run Azure CLI commands'
#        run: |
#          APIKEY=$(az staticwebapp secrets list --name hippo-booking-static-web-dev | jq -r '.properties.apiKey')
#          echo $APIKEY
