name: Main CI

on:
  push:
    branches: [ "main", "feat/ci-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    name: 'Build Back End API'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            src/**/packages.lock.json

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore --locked-mode

      - name: Build API
        working-directory: ./src
        run: dotnet build --no-restore

      - name: Run Core Unit Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Core.Tests.csproj --no-build --verbosity normal

      - name: Run Application Unit Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Application.Tests.csproj --no-build --verbosity normal

      - name: Run Infrastructure Unit Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Infrastructure.Tests.csproj --no-build --verbosity normal

      - name: Run Docker Compose
        run: docker compose -f src/infrastructure/docker/docker-compose-ci.yml up -d

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Run Integration Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Integration.Tests.csproj --no-build --verbosity normal

  build-frontend:
    name: 'Build Front End App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: install canvas
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ./src/web/hippo-booking

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
          dir: ./src/web/hippo-booking

      - name: Test the app
        uses: borales/actions-yarn@v5
        with:
          cmd: ci-test
          dir: ./src/web/hippo-booking

#      - name: Run Cypress Tests
#        working-directory: ./src/web/hippo-booking
#        run: |
#          npx cypress run --component

  e2e-tests:
    name: 'Run End-to-End Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            src/e2e/**/packages.lock.json

      - name: Restore dependencies
        working-directory: ./src/e2e/Hippo.Booking.E2ETests
        run: dotnet restore --locked-mode

      - name: Build E2E Tests
        working-directory: ./src/e2e/Hippo.Booking.E2ETests
        run: dotnet build --no-restore

      - name: Run Docker Compose
        run: docker compose -f infrastructure/docker/docker-compose-ci.yml -f infrastructure/docker/docker-compose-services.yml up -d

      - name: Run E2E Tests
        run: dotnet test e2e/**/Hippo.Booking.E2ETests.csproj --no-build --verbosity normal