name: Destroy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to deploy to'
        required: true
        default: 'Test'
        options:
          - 'Test'

jobs:

  deploy-infrastructure:
    name: 'Destroy ${{ github.event.inputs.environment }} Infrastructure'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/infrastructure/terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        id: init
        run: terraform init --backend-config="bucket=hippo-booking-terraform" --backend-config="key=terraform.${{ github.event.inputs.environment }}.tfstate" --backend-config="region=eu-west-1"

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
        env:
          TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TF_VAR_github_repo: https://github.com/${{ github.repository }}
          TF_VAR_github_access_token: ${{ secrets.FRONTEND_DEPLOY_TOKEN }}
          TF_VAR_slack_token: ${{ secrets.SLACK_TOKEN }}
          TF_VAR_slack_signing_secret: ${{ secrets.SLACK_SIGNING_SECRET }}
          TF_VAR_slack_channel_email: ${{ secrets.SLACK_CHANNEL_EMAIL }}