name: Nightly Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  run-jobs:
    name: 'Run Jobs'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Terraform Docs
        env:
            TERRAFORM_DOCS_VERSION: 0.18.0
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v${{ env.TERRAFORM_DOCS_VERSION }}/terraform-docs-v${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz
          tar -xvf terraform-docs-v${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz terraform-docs
          sudo mv terraform-docs /usr/local/bin/
          rm terraform-docs-v${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz

      - name: Generate TF Documentation
        run: terraform-docs markdown table src/infrastructure/terraform --output-file ../../../docs/Terraform.md

      - name: Dotnet Format
        working-directory: ./src
        run: dotnet format

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive

      - name: Commit changes
        run: |
          git config --global user.name 'Nightly Build Bot'
          git config --global user.email 'nightly-build-bot@users.noreply.github.com'
          git commit -am "Automated Nightly Jobs"
          git push
