name: AI Release Notes Generator

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.3.4, etc.

permissions:
  contents: write
  pull-requests: read

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai pygithub

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          python generate_release_notes.py --token ${{ secrets.GITHUB_TOKEN }} --gemini-api-key ${{ secrets.GEMINI_API_KEY }}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}