name: Validate - Front End

on:
  push:
    branches: [ "main", "feat/ci-test"  ]
    paths:
      - 'src/web/**'
      - '.github/workflows/validate-frontend.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/web/**'
      - '.github/workflows/validate-frontend.yaml'

jobs:
  build-frontend:
    name: 'Build Front End App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: install canvas
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ./src/web/hippo-booking

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
          dir: ./src/web/hippo-booking

      - name: Test the app
        uses: borales/actions-yarn@v5
        with:
          cmd: ci-test
          dir: ./src/web/hippo-booking

  #      - name: Run Cypress Tests
  #        working-directory: ./src/web/hippo-booking
  #        run: |
  #          npx cypress run --component
