name: Validate - Run E2E Tests

on:
  push:
    branches: [ "main", "feat/ci-test"  ]
    paths:
      - 'src/api/**'
      - 'src/web/**'
      - 'src/e2e/**'
      - 'src/infrastructure/docker/**'
      - '.github/workflows/validate-e2e.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/api/**'
      - 'src/web/**'
      - 'src/e2e/**'
      - 'src/infrastructure/docker/**'
      - '.github/workflows/validate-e2e.yaml'

jobs:
  e2e-tests:
    name: 'Run End-to-End Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            src/e2e/**/packages.lock.json

      - name: Restore dependencies
        working-directory: ./src/e2e/Hippo.Booking.E2ETests
        run: dotnet restore --locked-mode

      - name: Build E2E Tests
        working-directory: ./src/e2e/Hippo.Booking.E2ETests
        run: dotnet build --no-restore

      - name: Run Docker Compose
        run: docker compose -f infrastructure/docker/docker-compose-ci.yml -f infrastructure/docker/docker-compose-services.yml up -d

      - name: Run E2E Tests
        working-directory: ./src/e2e/Hippo.Booking.E2ETests
        run: dotnet test --no-build --verbosity normal --settings:chromium.runsettings