name: Validate - Back End API

on:
  push:
    branches: [ "main", "feat/ci-test"  ]
    paths:
      - 'src/api/**'
      - '.github/workflows/validate-backend.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/api/**'
      - '.github/workflows/validate-backend.yaml'

jobs:
  build-backend:
    name: 'Build Back End API'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            src/**/packages.lock.json

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore --locked-mode

      - name: Build API
        working-directory: ./src
        run: dotnet build --no-restore

      - name: Run Core Unit Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Core.Tests.csproj --no-build --verbosity normal

      - name: Run Application Unit Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Application.Tests.csproj --no-build --verbosity normal

      - name: Run Infrastructure Unit Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Infrastructure.Tests.csproj --no-build --verbosity normal

      - name: Run Docker Compose
        run: docker compose -f src/infrastructure/docker/docker-compose-ci.yml up -d

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Run Integration Tests
        run: dotnet test src/api/tests/**/Hippo.Booking.Integration.Tests.csproj --no-build --verbosity normal
